# Generated by Django 5.2.5 on 2025-08-06 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("recommendation_emails", models.BooleanField(default=True)),
                ("include_adult_content", models.BooleanField(default=False)),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                ("enable_collaborative_filtering", models.BooleanField(default=True)),
                ("enable_content_based_filtering", models.BooleanField(default=True)),
                ("recommendation_diversity", models.FloatField(default=0.5)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view_movie", "View Movie"),
                            ("rate_movie", "Rate Movie"),
                            ("add_favorite", "Add to Favorites"),
                            ("remove_favorite", "Remove from Favorites"),
                            ("add_watchlist", "Add to Watchlist"),
                            ("remove_watchlist", "Remove from Watchlist"),
                            ("search", "Search"),
                            ("view_recommendations", "View Recommendations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("movie_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="users_usera_user_id_421934_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="users_usera_timesta_6dbdeb_idx"
                    ),
                    models.Index(
                        fields=["movie_id"], name="users_usera_movie_i_a276f6_idx"
                    ),
                ],
            },
        ),
    ]
